In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt

def add_naive_forecast(df, target_col, months_back, start_date, horizon_months, text):
  
    forecast_col = f"Naive: {months_back}-Month for {text}"
    df[forecast_col] = np.nan

    start = pd.to_datetime(start_date)
    end = start + pd.DateOffset(months=horizon_months - 1)
    reference_date = start - pd.DateOffset(months=months_back)

    if reference_date in df.index:
        naive_value = df[target_col][df.index < start_date].iloc[-1]
        forecast_range = (df.index >= start) & (df.index <= end)
        df.loc[forecast_range, forecast_col] = naive_value

    return df

In [4]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt

file_path = "cleandata.csv"
df_clean = pd.read_csv(file_path)

df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%b-%Y')
df_clean = df_clean.sort_values(by='Date').set_index('Date')
target = 'LNG 174K CBM (2-stroke dual fuel) Spot Rate (avg., $/day)'

df_forecast = df_clean[[target]].copy()
df_forecast.loc[df_forecast.index >= '2024-01-01', "Actual Rate"] = (df_forecast[target].loc[df_forecast.index >= '2024-01-01'])
df_forecast.loc[df_forecast.index >= '2024-01-01', "Naive: 1-Month"] = (df_forecast[target].shift(1).loc[df_forecast.index >= '2024-01-01'])

# Create 3-month naive forecast starting Jan 2024, filling Jan-Mar 2024
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-01-01', horizon_months=3, text="Jan-Mar")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-02-01', horizon_months=3, text="Feb-Apr")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-03-01', horizon_months=3, text="Mar-May")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-04-01', horizon_months=3, text="Apr-Jun")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-05-01', horizon_months=3, text="May-Jul")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-06-01', horizon_months=3, text="Jun-Aug")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-07-01', horizon_months=3, text="Jul-Sep")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-08-01', horizon_months=3, text="Aug-Oct")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-09-01', horizon_months=3, text="Sep-Nov")
df_forecast = add_naive_forecast(df_forecast, target, months_back=3, start_date='2024-10-01', horizon_months=3, text="Oct-Dec")
# Create 6-month naive forecast starting Jan 2024, filling Jan-Jun 2024
df_forecast = add_naive_forecast(df_forecast, target, months_back=6, start_date='2024-01-01', horizon_months=6, text="Jan-Jun")
df_forecast = add_naive_forecast(df_forecast, target, months_back=6, start_date='2024-02-01', horizon_months=6, text="Feb-Jul")
df_forecast = add_naive_forecast(df_forecast, target, months_back=6, start_date='2024-03-01', horizon_months=6, text="Mar-Aug")
df_forecast = add_naive_forecast(df_forecast, target, months_back=6, start_date='2024-04-01', horizon_months=6, text="Apr-Sep")
df_forecast = add_naive_forecast(df_forecast, target, months_back=6, start_date='2024-05-01', horizon_months=6, text="May-Oct")
df_forecast = add_naive_forecast(df_forecast, target, months_back=6, start_date='2024-06-01', horizon_months=6, text="Jun-Nov")
df_forecast = add_naive_forecast(df_forecast, target, months_back=6, start_date='2024-07-01', horizon_months=6, text="Jul-Dec")

df_forecast.dropna()
display(df_forecast)


#print("MAE 1M:", df_metrics["Naive: 1-Month: error"].abs().sum()/df_metrics["Naive: 1-Month: error"].count())
#print("RMSE 1M", np.sqrt((df_metrics["Naive: 1-Month: error"]**2).sum()/df_metrics["Naive: 1-Month: error"].count()))

#print("MAE 3M:", df_metrics["Naive: 3-Month: error"].abs().sum()/df_metrics["Naive: 3-Month: error"].count())
#print("RMSE 3M", np.sqrt((df_metrics["Naive: 3-Month: error"]**2).sum()/df_metrics["Naive: 3-Month: error"].count()))

#print("MAE 6M:", df_metrics["Naive: 6-Month: error"].abs().sum()/df_metrics["Naive: 6-Month: error"].count())
#print("RMSE 6M", np.sqrt((df_metrics["Naive: 6-Month: error"]**2).sum()/df_metrics["Naive: 6-Month: error"].count()))

#print("MAE 12M:", df_metrics["Naive: 12-Month: error"].abs().sum()/df_metrics["Naive: 12-Month: error"].count())
#print("RMSE 12M", np.sqrt((df_metrics["Naive: 12-Month: error"]**2).sum()/df_metrics["Naive: 12-Month: error"].count()))

,"LNG 174K CBM (2-stroke dual fuel) Spot Rate (avg., $/day)",Actual Rate,Naive: 1-Month,Naive: 3-Month for Jan-Mar,Naive: 3-Month for Feb-Apr,Naive: 3-Month for Mar-May,Naive: 3-Month for Apr-Jun,Naive: 3-Month for May-Jul,Naive: 3-Month for Jun-Aug,Naive: 3-Month for Jul-Sep,Naive: 3-Month for Aug-Oct,Naive: 3-Month for Sep-Nov,Naive: 3-Month for Oct-Dec,Naive: 6-Month for Jan-Jun,Naive: 6-Month for Feb-Jul,Naive: 6-Month for Mar-Aug,Naive: 6-Month for Apr-Sep,Naive: 6-Month for May-Oct,Naive: 6-Month for Jun-Nov,Naive: 6-Month for Jul-Dec
Date,,,,,,,,,,,,,,,,,,,,
2019-01-01,91358.125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-02-01,68721.750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-01,48349.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-04-01,48500.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-05-01,64600.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-01,76800.000,76800.0,75562.5,NaN,NaN,NaN,NaN,NaN,50700.0,63312.5,75562.5,NaN,NaN,NaN,NaN,52375.0,53950.0,47562.5,50700.0,63312.5
2024-09-01,67000.000,67000.0,76800.0,NaN,NaN,NaN,NaN,NaN,NaN,63312.5,75562.5,76800.0,NaN,NaN,NaN,NaN,53950.0,47562.5,50700.0,63312.5
2024-10-01,45312.500,45312.5,67000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75562.5,76800.0,67000.0,NaN,NaN,NaN,NaN,47562.5,50700.0,63312.5
2024-11-01,26600.000,26600.0,45312.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76800.0,67000.0,NaN,NaN,NaN,NaN,NaN,50700.0,63312.5
2024-12-01,23000.000,23000.0,26600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67000.0,NaN,NaN,NaN,NaN,NaN,NaN,63312.5

In [ ]:
import pandas as pd
import numpy as np

# Load the clean data
file_path = "cleandata.csv"
df_clean = pd.read_csv(file_path)

df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%b-%Y')
df_clean = df_clean.sort_values(by='Date').set_index('Date')
target = 'LNG 174K CBM (2-stroke dual fuel) Spot Rate (avg., $/day)'

# Prepare the corrected long format dataframe
forecast_types = [(1, "1-Month"), (3, "3-Month"), (6, "6-Month"), (12, "12-Month")]
forecast_rows = []

# Extract actual rates
for index, row in df_clean.iterrows():
    actual_rate = row[target]
    if pd.notna(actual_rate):
        forecast_rows.append([index, actual_rate, index.strftime("%b"), np.nan, np.nan, np.nan, np.nan])

# Generate naive forecasts including 12-month, limited to 2024-12-01
forecast_end_date = pd.Timestamp("2024-12-01")

for start_date in pd.date_range('2024-01-01', '2024-12-01', freq='MS'):
    forecast_row = {
        "Date": start_date,
        "Actual Rate": np.nan,
        "Forecast Start Month": start_date.strftime("%b"),
        "1-Month Forecast": np.nan,
        "3-Month Forecast": np.nan,
        "6-Month Forecast": np.nan,
        "12-Month Forecast": np.nan
    }
    
    for months_back, forecast_label in forecast_types:
        reference_date = start_date - pd.DateOffset(months=months_back)
        
        # Only add a forecast if the reference date exists
        if reference_date in df_clean.index:
            naive_value = df_clean.loc[reference_date, target]
            horizon_months = 3 if forecast_label == "3-Month" else 6 if forecast_label == "6-Month" else 12 if forecast_label == "12-Month" else 1
            end_date = min(start_date + pd.DateOffset(months=horizon_months - 1), forecast_end_date)
            forecast_range = pd.date_range(start_date, end_date, freq='MS')

            for forecast_date in forecast_range:
                # Ensure this date exists in the final forecast row
                if forecast_date == start_date:
                    forecast_row[f"{forecast_label} Forecast"] = naive_value
    
    forecast_rows.append(list(forecast_row.values()))

# Create the final structured dataframe
columns = ["Date", "Actual Rate", "Forecast Start Month", "1-Month Forecast", "3-Month Forecast", "6-Month Forecast", "12-Month Forecast"]
df_final = pd.DataFrame(forecast_rows, columns=columns)
df_final = df_final.dropna(subset=["1-Month Forecast", "3-Month Forecast", "6-Month Forecast", "12-Month Forecast"], how="all")
df_final = df_final.sort_values(by="Date")
display(df_final)
#df_final.to_csv("final_cleaned_forecast_data.csv", index=False)
print("Forecast data generated and saved.")

,Date,Actual Rate,Forecast Start Month,1-Month Forecast,3-Month Forecast,6-Month Forecast,12-Month Forecast
72,2024-01-01,NaN,Jan,139750.0,184375.0,92562.5,119937.5
73,2024-02-01,NaN,Feb,69750.0,197500.0,137500.0,90000.0
74,2024-03-01,NaN,Mar,52375.0,139750.0,232750.0,83000.0
75,2024-04-01,NaN,Apr,53950.0,69750.0,184375.0,68750.0
76,2024-05-01,NaN,May,47562.5,52375.0,197500.0,61812.5
77,2024-06-01,NaN,Jun,50700.0,53950.0,139750.0,80850.0
78,2024-07-01,NaN,Jul,63312.5,47562.5,69750.0,92562.5
79,2024-08-01,NaN,Aug,75562.5,50700.0,52375.0,137500.0
80,2024-09-01,NaN,Sep,76800.0,63312.5,53950.0,232750.0
81,2024-10-01,NaN,Oct,67000.0,75562.5,47562.5,184375.0
82,2024-11-01,NaN,Nov,45312.5,76800.0,50700.0,197500.0
83,2024-12-01,NaN,Dec,26600.0,67000.0,63312.5,139750.0

Forecast data generated and saved.